_BASE_: "Base-Panoptic-Contour.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  CONTOUR_NET:
    ARCH: seperate_blocks
  CONTOUR_HEAD:
    LOSS_WEIGHT: 50.0
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "output/cityscapes_panoptic_contour_binary_seperate_blocks_R_50_1x"
SOLVER:
  IMS_PER_BATCH: 2
