_BASE_: "Base-Panoptic-Contour.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  HED_HEAD:
    RES5_SUPERVISION: True
OUTPUT_DIR: "output/cityscapes_panoptic_contour_binary_seperate_R_50_1x_res5supervision"

