_BASE_: "Base-Panoptic-Contour.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  CONTOUR_HEAD:
    NUM_CLASSES: 8
    LOSS_WEIGHT: 50.0
    HUBER_ACTIVE: "False"
    DICE_ACTIVE: "False"
  RESNETS:
    DEPTH: 50
SOLVER:
  BASE_LR: 0.01
  STEPS: (54000,66000)
  MAX_ITER: 80000
  IMS_PER_BATCH: 4
OUTPUT_DIR: "output/cityscapes_panoptic_contour_multi_seperate_R_50_3x"

