_BASE_: "Base-Panoptic-Contour.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  HED_HEAD:
    NUM_CLASSES: 8
  RESNETS:
    DEPTH: 50
  CONTOUR_NET:
    LOSS_COMBINATION: "uncertainty"
OUTPUT_DIR: "output/cityscapes_panoptic_contour_multi_seperate_R_50_1x_uncertainty"
