_BASE_: "Base-Panoptic-Contour.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  CONTOUR_HEAD:
    DICE_ACTIVE: "True"
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "output/cityscapes_panoptic_contour_binary_seperate_R_50_1x_bce_dice_huber"
